/*
-- Query: SELECT * FROM area_de_notas
LIMIT 0, 1000

-- Date: 2016-02-04 12:42
*/
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-4-1','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-4-2','Hay dos dvds, el tono en el que se ven es virado a azul. http://metamentaldoc.com/ft_grierson.pdf ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-4-3','Se encuentra en línea con buena resolución: https://www.youtube.com/watch?v=CRssZLdJAvA');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-4-4','El DVD esta en español y el VHS en inglés. ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-4-5','En el mismo DVD, se encuentran tres títulos \"A Valparaíso\" 26\'38\'\', Nogent 14\'57\'\' y Van Gogh 17\'55\'\'');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-4-6','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-1','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-3','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-4','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-5','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-6','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-7','El dvd contiene además un documental \"Des idees, des hommes, des ouvres\" con duración de 30\'');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-8','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-9','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-10','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 946.077 TIE.e');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-11','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-12','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-13','Falla entre el minuto 19:40 y 24:00 se interrumpe la reproducción, reanudar la reproducción despues de ese minuto, manualmente');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-14','Películas restauradas por la Dirección de Proyectos e Iniciativas Culturales. Consejería de Presidencia. Comunidad Autónoma Región de Murcía y \"MURCIA CULTURAL, S.A.\" De 1931 a 1935 Val del Omar realizó centenares de fotografías y decenas de películas documentales sobre la labor de las MISIONES PEDAGÓGICAS y su MUSEO DEL PUEBLO. Muchas de las fotografías  fueron publicadas en las Memorias del Patronato de Misiones y en la revista de la Residencia de Estudiantes pero casi todas las películas están todavía desaparecidas.  Cristóbal Simancas, ayudante y amigo de Val del Omar, conservó durante toda su vida las copias en positivo directo de este valioso material. Estas copias han subsistido a distintas etapas históricas y geográficas: desde la guerra civil en Madrid, la larga estancia de Simancas en Caracas (Venezuela) y finalmente su retiro en La Nucia (Alicante). En 1994 Cristóbal Simancas las donó a María José Val Del Omar a cuyo recuerdo está dedicada esta restauración. Los audiovisuales  no se encuentran físicamente');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-5-16','No se encuentra físicamente');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-1','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-3','Virado a verde');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-4','http://www.divxclasico.com/foro/viewtopic.php?t=25213');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-5','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-6','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-7','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-8','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-9','En el mismo disco se puede encontrar México Durante el siglo XIX, con duración de 6\'57\'\' de Carlos Benegri / Cine Mundial del año 1959, duración 7 minutos, de Fabian Arnaud Jy t Ruben G Chacón y México Hacia el Futuro del año 1949, es el tercer corto de 19\' 18\'\' de la Comisión Nacional de Cinematografía.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-10','Tiene algunos defectos de desgaste en la grabación, pero se puede ver completo. Para hacer portada se uso información del sitio http://cine.zaragozame.com/alain-resnais-la-libertad/');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-11','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-12','En el mismo disco se puede encontrar México Durante el siglo XIX, con duración de 6\'57\'\' de Carlos Benegri / Cine Mundial del año 1959, duración 7 minutos, de Fabian Arnaud Jy t Ruben G Chacón y México Hacia el Futuro del año 1949, es el tercer corto de 19\' 18\'\' de la Comisión Nacional de Cinematografía.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-6-13','En el mismo disco se puede encontrar México Durante el siglo XIX, con duración de 6\'57\'\' de Carlos Benegri / Cine Mundial del año 1959, duración 7 minutos, de Fabian Arnaud Jy t Ruben G Chacón y México Hacia el Futuro del año 1949, es el tercer corto de 19\' 18\'\' de la Comisión Nacional de Cinematografía.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-1','Copia. Calidad de imagen mala. Con código de tiempo');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-3','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-4','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-5','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-6','http://www.der.org/films/mammy-water.html');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-7','Se corta a los 80\'');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-8','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-9','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-10','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-11','http://cinestonia.blogspot.mx/2011/09/guernica-1950-alain-resnais.html');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-7-12','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-1','Está en un compilado de la década de los 50 MXIM-AV-1-7-7');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-3','No se encuentran físicamente en el acervo');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-4','No se encuentran físicamente en el acervo  ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-6','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-7','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-8','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-9','Película documental grabada desde la televisión, en el canal TVE (Televisión Española)');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-10','Viene un corto Tom Tom The pipper\'s con duración 10 min');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-11','No se encuentran físicamente en el acervo');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-12','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-13','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-14','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-15','Falta hacer copia individual en DVD');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-16','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-17','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-18','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-19','No se encuentran físicamente en el acervo');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-20','http://sensesofcinema.com/2010/great-directors/jean-rouch/');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-21','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-22','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-23','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-24','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 791.4353 MEX.b');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-25','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 946.077 MOR.e');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-26','En este DVD están dos noticieros: MUERTE AL INVASOR y LA DECLARACION DE LA HABANA');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-27','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-28','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-29','No se encuentran físicamente en el acervo');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-30','http://tierraentrance.miradas.net/2014/11/ensayos/docunoticieros-muerte-al-invasor-y-ii-declaracion-de-la-habana-consideraciones-acerca-del-cine-informativo-cubano.html');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-31','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-32','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-33','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-8-34','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-1','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-3','Película documental grabada desde la televisión, canal TVE.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-4','Tiene un extracto de un corto La natatión de tres minutos, incompleto.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-5','https://spanishinmotion.wordpress.com/ojo-critico/ojo-criticocanciones-para-despues-de-una-guerra/');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-6','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-7','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 791.4353 HIS.d');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-8','http://www.margencero.com/musica/jara/birmania%202.htm, el dvd tiene las dos partes, la segunda del golpe de Estado está incompleta.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-9','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-10','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-11','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-12','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-13','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-14','Película documental con imagen degradada (DROP)');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-15','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-16','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-17','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-18','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-19','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-20','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-21','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-22','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-23','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-24','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-25','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-26','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-27','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-28','El corto documental esta en el mismo DVD de Under the men\'s tree.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-29','El corto documental esta en el mismo DVD de Under the men\'s tree.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-9-30','El documental \"El desencanto\" tenia el mismo códico de \"Historias de un documento\" MXIM-AV-1-09-7, y en la base de datos se corroboró que la información del código era de \"Historias de un documento\".');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-1','Existe un VHS, pero tiene algunas fallas, quizá solo sea de origen o limpieza');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-3','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-4','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-5','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-6','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-7','Tiene algunas fallas de origen, pero se ve completo.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-8','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-9','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-10','Tiene algunas fallas de origen, pero se ve completo.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-11','En el mismo disco aparece el documental de El Blanquita');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-12','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-13','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-14','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-15','Aparecen varios documentales o cortos del mismo director.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-16','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-17','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-18','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-19','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-20','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-21','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-22','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-23','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-24','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-25','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-26','Suplementos y características especiales: 1) Opción de acceder directamente a un pasaje del documental centrado en el mezcal (2 minutos y medio) y 2-3) Pantallas de texto con opiniones de Manuel Aguilar de la Torre, Patricia Vega, Alberto Híjar y Florence Toussaint, aparecidas original y respectivamente en las publicaciones Excélsior, La Jornada, El Día y Proceso, sobre el mediometraje y lista de premios otorgados al documental. \nMaterial audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 791.430971 MAL.1');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-27','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-28','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 923.6 MIH.e');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-29','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-30','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-31','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-32','El disco (DVD) contiene un fragmento de Fait Divers también de Raymond Depardon');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-33','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-34','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-35','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-36','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-37','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-38','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-39','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-40','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-41','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-42','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-43','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-44','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-45','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-46','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-47','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-48','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-140');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-49','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-140');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-50','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-140');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-51','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-140');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-52','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-140');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-53','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-140');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-54','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-141');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-55','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-141');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-56','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-141');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-57','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-141');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-58','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-141');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-59','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-142');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-60','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-142');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-61','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-142');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-62','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-142');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-63','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-142');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-64','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-143');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-65','La serie se encuentra en físico en la década 2000 con la clasificación MXIM-AV-1-12-143');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-66','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-67','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-68','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-69','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-70','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-71','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-72','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-73','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-74','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-75','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-76','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-77','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-78','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-79','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-80','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-81','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-82','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-83','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-84','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-85','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-86','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-10-87','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-1','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-3','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-4','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-5','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-6','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-7','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-8','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-9','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-10','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-11','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-12','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-13','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-14','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-15','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-16','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-17','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 781.77291 BUE.v');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-18','Inicia con otro video sin audio que dura aproximadamente 4´');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-19','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-20','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 303.64 CHI.d');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-21','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 972.750639 CHI.a V.2');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-22','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 972.00497 CHI.l');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-23','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 972.750639 CHI.a v.1');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-24','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-25','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-26','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-27','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-28','http://misteriosoobjetoalmediodia.wordpress.com/2008/02/13/close-up-abbas-kiarostami-1990/            http://www.imdb.com/title/tt0100234/');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-29','Se registro en el área de \"recursos\" la puesta en escena, pero hay que aclarar que dicho recurso es con fine promocionales');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-30','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-31','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-32','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 305.42 CUA.y');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-33','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-34','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-35','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-36','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-37','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 791.430972 DEL.o');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-38','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-39','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-40','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 320.94310878 DIE.m');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-41','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-42','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-43','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-44','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-45','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-46','Copia grabada desde la televisión, contiene comerciales.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-47','Tiene código de tiempo');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-48','Copia grabada desde la televisión, contiene comerciales.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-49','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-50','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-51','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-52','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-53','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-53-1','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-53-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-54','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-55','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-56','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-57','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-58','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-59','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-60','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-61','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-62','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 982 HIS.a v.0');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-63','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 982 HIS.a v.1');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-64','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 982 HIS.a v.2');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-65','Copia de televisión.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-66','En la caja del DVD traía el código MXIM-AV-1-11-159');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-67','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-68','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-69','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-70','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-71','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-72','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-73','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-74','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-75','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 322.44 BAT.d');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-76','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-77','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-78','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-79','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 972.00497 GUE.d');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-80','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-81','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-82','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-83','Copia que contiene otros documentales. Se corta en el minuto 122´35\" sin haberse terminado el documental. ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-84','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-85','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-86','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-87','Copia de la televsión');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-88','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-89','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-90','Copia grabada desde la televisión. El inicio está cortado.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-91','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-92','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-93','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-94','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-94-1','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-94-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-95','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-96','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-97','Copia grabada desde la televisión. El inicio está incompleto.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-98','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-99','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 303.64 MAR.m');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-100','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-101','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-102','Una de las copias contiene el libro: Toscano, Carmen, Memorias de un mexicano, México, Fundación Carmen Toscano, 1996, 156 pp.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-103','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-104','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-105','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-106','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 322.44 MEX.s ej.2');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-107','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-108','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-109','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 356.15 MON.t');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-110','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-111','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-112','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-113','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-114','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-115','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-116','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-117','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-118','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 725.822 PAL.e');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-119','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-120','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-121','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-122','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-123','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 972.06 REV.po');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-124','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-125','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-126','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-127','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-128','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-129','Es una copia incompleta de la televisión ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-130','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-131','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-132','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 923.672 JAR.m');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-133','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-134','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-135','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-136','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-137','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-138','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-139','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-140','Copia programa de televisón incompleto y con fallas.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-141','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-142','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-143','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-144','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-145','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-146','Incompleto. Se corta a los 158´');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-147','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-148','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 303.64 TOD.s');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-149','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-150','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 304.872 UNB.a');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-151','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-152','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-153','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-154','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-155','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-156','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-157','El cortometraje se encuentra en el dvd MXIM-AV-1-12-4');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-158','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-159','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-160','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-161','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-162','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-163','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-164','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-165','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-166','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-167','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-168','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-169','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-170','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-171','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-172','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-173','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-174','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-175','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-176','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-177','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-178','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-179','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-180','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-181','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-182','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-183','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-184','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-185','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-186','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-187','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-188','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-189','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-190','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-191','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-192','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-193','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-194','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-195','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-196','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-197','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-198','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-199','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-200','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-201','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-202','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-203','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-204','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-205','Documental incompleto.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-206','Contiene un folleto informativo escrito por el arqueólogo Roberto García Moll, con bibliografía y mapas');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-207','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-208','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-209','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-210','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-211','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-212','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-213','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-214','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-215','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-216','El vídeo al inicio tiene algunas fallas de origen, y en el minuto 28 deja de producir imagen. ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-11-217','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-1','Este material audiovisual  forma parte del \"material extra\" de la  edición de las películas La Jetée y Sans Soleil de Chris Marker que se encuentran ta,bién en el acervo de docuemntal en video del LAIS con el código de referencia MXIM-AV-1-8-18');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-3','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-4','Películas restauradas por la Dirección de Proyectos e Iniciativas Culturales. Consejería de Presidencia. Comunidad Autónoma Región de Murcía y \"MURCIA CULTURAL, S.A.\"                    De 1931 a 1935 Val del Omar realizó centenares de fotografías y decenas de películas documentales sobre la labor de las MISIONES PEDAGÓGICAS y su MUSEO DEL PUEBLO. Muchas de las fotografías  fueron publicadas en las Memorias del Patronato de Misiones y en la revista de la Residencia de Estudiantes pero casi todas las películas están todavía desaparecidas.  Cristóbal Simancas, ayudante y amigo de Val del Omar, conservó durante toda su vida las copias en positivo directo de este valioso material. Estas copias han subsistido a distintas etapas históricas y geográfucas: desde la guerra civil en Madrid, la larga estancia de Simancas en Caracas (Venezuela) y finalmente su retiro en La Nucia (Alicante). En 1994 Cristóbal Simancas las donó a María José Val Del Omar a cuyo recuerdo está dedicada esta restauración.    El DVD támbien contiene Acariño galaico (de barro)  MXIM-AV-1-11-157');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-5','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-6','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 791.43 PRO.d');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-7','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-8','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-9','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-10','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-11','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-12','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-13','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-14','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 322.42 CHI.l');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-15','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-16','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-17','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-18','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-19','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-20','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-21','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-22','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-23','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-24','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-25','La caja contiene 2 discos rotulados como \"Disco 1\" y \"Disco 2\". Sin embargo contienen el mismo material; es decir, son 2 copias iguales. En la contraportada se tienen registrados 10 documentales de los cuales se cuenta  únicamente con 4.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-26','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-27','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-28','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-29','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-30','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 782.42166 FIL.a');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-31','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-32','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-33','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-34','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-35','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-36','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-37','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-38','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-39','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-40','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-41','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-42','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 305.892705694 OTR.m');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-43','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-44','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-45','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-46','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-47','Documental transmitido por el canal 22 y videograbado para su inclusión en el acervo del LAIS. Contiene comerciales.  La videograbación no está completa.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-48','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-49','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-50','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-51','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-52','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-53','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-54','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-55','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-55-3','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-56','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-57','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-58','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 973.93 FAH.r');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-59','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-60','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-61','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 324.97200641 FRA.u');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-62','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 364.151 CAV.e');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-63','En el minuto 8´05\"   se corta y reinicia en 8´44\"');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-64','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-65','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-66','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-67','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-68','https://formacritica34013.wordpress.com/2013/07/17/analisis-de-la-pelicula-historias-cruzadas/');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-69','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-70','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-71','La estatua de El Caballito (1950´s)');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-72','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-73','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-74','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-75','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-76','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-77','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-78','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-79','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-80','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-81','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-82','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-83','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-84','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-85','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 972,00497 LAC.m');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-86','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 305.42 CON.h');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-87','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-88','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-89','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-90','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-91','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-92','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-93','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-94','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-95','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-96','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-97','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-98','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-99','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-100','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-101','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-102','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-103','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-104','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-105','Programa de Canal 22 basado en los libros Tragicomedia mexicana de José Agustín. Material audiovisual  grabado directamente desde la televisión.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-106','Programa de Canal 22 basado en los libros Tragicomedia mexicana de José Agustín. Material audiovisual  grabado directamente desde la televisión.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-107','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-108','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-109','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-110','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-111','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-112','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-113','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-114','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-115','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-116','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-117','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-118','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-119','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-120','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-121','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-122','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-123','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-124','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-125','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-126','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 725827 MAS.a');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-127','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-128','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-129','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-130','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-131','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-132','3a parte de la trilogía Qatsi');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-133','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-134','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-135','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-136','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 616.398 NIÑ.c');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-137','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-138','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-139','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-140','Revisar los datos registrados en la base de datos de 1980. Desde MXIM-AV-1-10-48 a MXIM-AV-1-10-65 ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-141','Revisar los datos registrados en la base de datos de 1980. Desde MXIM-AV-1-10-48 a MXIM-AV-1-10-65 ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-141-6','Revisar los datos registrados en la base de datos de 1980. Desde MXIM-AV-1-10-48 a MXIM-AV-1-10-65 ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-141-7','Revisar los datos registrados en la base de datos de 1980. Desde MXIM-AV-1-10-48 a MXIM-AV-1-10-65 ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-141-8','Revisar los datos registrados en la base de datos de 1980. Desde MXIM-AV-1-10-48 a MXIM-AV-1-10-65 ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-142','Revisar los datos registrados en la base de datos de 1980. Desde MXIM-AV-1-10-48 a MXIM-AV-1-10-65 ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-143','Revisar los datos registrados en la base de datos de 1980. Desde MXIM-AV-1-10-48 a MXIM-AV-1-10-65 ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-144','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-145','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 305.42 LUC.d');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-146','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-147','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-148','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-149','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-150','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-151','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-152','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-153','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 791.4353 POW.t');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-154','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-155','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-156','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-157','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-158','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-159','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-160','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-161','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-162','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-163','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-164','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-165','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-166','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 791.430944 SOB.i');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-167','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-168','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-169','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 322.4 VIV.I');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-170','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV  394.1 SUP.s');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-171','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-172','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-173','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-174','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-175','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-176','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-177','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-178','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-179','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-180','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 791.43032244 TLA.t');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-181','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-182','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-183','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-184','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-185','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-186','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-187','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-1','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-2','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-3','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-4','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-5','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-6','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-7','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-8','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-9','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-188-10','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-189','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-190','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-191','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-192','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-193','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-194','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-195','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-196','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-197','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-198','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-199','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.1');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-200','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.1');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-201','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.2');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-202','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.2');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-203','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.3');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-204','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.3');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-205','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.4');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-206','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.4');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-207','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.5');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-208','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.5');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-209','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.6');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-210','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 785.0667 JAZ.z v.6');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-211','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-212','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-213','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-214','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-215','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-216','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-217','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-218','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-219','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-220','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-221','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-222','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-223','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-224','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-225','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-226','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-227','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-228','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-229','Cine observacional');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-230','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-231','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-232','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-233','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-234','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-235','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-236','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-237','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-238','Incluye folleto con sugerencias pedagógicas, elaborado por Diana Hamra y Felipe Pigna,   Argentina, Diana Producciones, 22 pp. ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-239','Incluye folleto con sugerencias pedagógicas, elaborado por Diana Hamra y Felipe Pigna,   Argentina, Diana Producciones, 22 pp. ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-240','Incluye folleto con sugerencias pedagógicas, elaborado por Diana Hamra y Felipe Pigna,   Argentina, Diana Producciones, 22 pp. ');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-241','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-242','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-243','Material audiovisual registrado en la base de datos de la Biblioteca Ernesto de la Torre Villar, Instituto Mora. Código de referencia: VV 364.1523 SEÑ.e');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-244','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-245','Se traba');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-246','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-247','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-248','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-249','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-250','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-251','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-252','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-253','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-254','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-255','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-256','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-257','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-258','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-259','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-260','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-261','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-262','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-263','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-264','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-265','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-266','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-267','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-268','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-269','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-270','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-271','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-272','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-273','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-274','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-275','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-276','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-277','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-278','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-279','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-280','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-281','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-282','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-283','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-284','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-285','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-286','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-287','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-288','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-289','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-290','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-291','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-292','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-293','Este film se encuentra en el disco MXIM-AV-1-12-292');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-294','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-295','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-296','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-297','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-298','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-299','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-300','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-301','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-302','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-303','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-304','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-305','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-306','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-307','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-308','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-309','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-310','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-311','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-312','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-313','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-314','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-315','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-316','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-317','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-318','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-319','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-320','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-321','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-322','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-323','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-324','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-325','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-326','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-327','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-328','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-329','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-330','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-331','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-332','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-333','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-334','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-335','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-336','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-337','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-338','Este film esta documentado en la década de 1990 con el código MXIM-AV-1-11-210');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-339','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-340','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-341','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-342','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-343','VIDEO \nestándar 1.33:1 [04:03]\nAUDIO \nFrancés Dolby Stereo\n\nLEYENDAS \nPortugués   Frances\n\nOPCIONES ESPECIALES \n. Biografía y filmografía del director Jean Rouch \n. Análisis de las películas');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-344','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-345','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-346','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-347','Existen dos discos de este documental, uno en inglés y otro en portugués.');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-348','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-349','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-350','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-351','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-352','');
INSERT INTO `area_de_notas` (`codigo_de_referencia`,`area_de_notas`) VALUES ('MXIM-AV-1-12-353','');
